# Generated by Django 5.0.2 on 2024-05-08 10:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_location', models.CharField(choices=[('J', 'Jours'), ('S', 'Semaines'), ('M', 'Mois'), ('Vente', 'Vente')], default='Mois', max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('est_disponible', models.BooleanField(default=True)),
                ('ajout_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biens.categories')),
            ],
        ),
    ]
